version: "3.7"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: nodejs_server:latest
    ports:
      - "3000:3000"
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
    env_file:
      - .env
    depends_on:
      - mysql_db
      - adminer
    volumes:
      - ./src:/usr/src/app/src
  mysql_db:
    image: mysql:9.0.0
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
  adminer:
    image: adminer:4.8.1
    restart: always
    depends_on:
      - mysql_db
    ports:
      - 8080:8080
volumes:
  mysql-data:
