FROM node:20.6.1

RUN npm install -g pnpm

WORKDIR /usr/src/app

COPY package*.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

RUN chmod +x ./start.sh

EXPOSE ${PORT}

ENTRYPOINT ["./start.sh"]



